# Based on http://conda.pydata.org/docs/travis.html
language: python
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - python: 2.6
    env: UPDATE_ENV="conda install unittest2"
  - python: 2.7
  - python: 3.3
  - python: 3.4

before_install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  # note: for now, install numba from source so we get fixes on master
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION nose python cython
  - source activate test_env
  - echo $UPDATE_ENV; $UPDATE_ENV
  - python setup.py build_ext --inplace --with-cython

script:
  - nosetests
